server:
  port: 9090
  servlet:
    context-path: /yingx
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingx
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  #redis:
    #host: 192.168.44.141  #ip地址
    #port: 7000   #端口
    #database: 3 #操作的库


  data:
    elasticsearch:
      cluster-nodes: 192.168.44.143:9300
mybatis:
  type-aliases-package: com.baizhi.bqs.entity
  mapper-locations: classpath:com/baizhi/bqs/mapper/*.xml
